services:
  # backend:
  #   build: ./backend
  #   ports:
  #     - "8000:8000"
  #   volumes:
  #     - ./backend:/app
  #     - ./backend/data:/app/data

  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules   # keeps container's own node_modules, avoids host overwrite
    depends_on:
      - backend